import course
import song

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='repl.it',
                  resource_url='https://repl.it/'),
    course.Course(period=2,
                  name='U.S. History',
                  teacher_name='Mr. Killeen',
                  resource_name='ArtHistory.net',
                  resource_url='http://www.arthistory.net/'),
    course.Course(period=3,
                  name='AP Lang',
                  teacher_name='Mrs. Pacia-McCann',
                  resource_name='Spark Notes',
                  resource_url='http://www.sparknotes.com/'),
    course.Course(period=4,
                  name='Algebra 2',
                  teacher_name='Ms. Song',
                  resource_name='Khan Academy',
                  resource_url='https://www.khanacademy.org/math/geometry/'),
    course.Course(period=5,
                  name='Biotechnology',
                  teacher_name='Mr. Ng',
                  resource_name='Active Simuations',
                  resource_url='https://phet.colorado.edu/en/simulations/category/physics'),
    course.Course(period=6,
                  name='Art 1',
                  teacher_name='Ms. Hoover',
                  resource_name='Wikipedia',
                  resource_url='https://en.wikipedia.org/wiki/Biology'),
]

TOP_TEN_SONGS = [
    song.Song(title="Ric Flair Drip",
            artist_name="Offset and Metro Boomin",
            youtube_url="https://www.youtube.com/watch?v=OwbI9IY9Roo"),
    song.Song(title="Gyalchester",
            artist_name="Drake",
            youtube_url="https://www.youtube.com/watch?v=smbz9w3dMXk&index=294&list=LLTMldtPNnazX0I1Y1Mctdfg"),
    song.Song(title="Poison",
            artist_name="BBD",
            youtube_url="https://www.youtube.com/watch?v=RHFVIH-TewM&index=222&list=LLTMldtPNnazX0I1Y1Mctdfg"),
    song.Song(title="Psycho",
            artist_name="Post Malone",
            youtube_url="https://www.youtube.com/watch?v=UuCimrKxKFk&list=LLTMldtPNnazX0I1Y1Mctdfg&index=126"),
    song.Song(title="God's Plan",
            artist_name="Drake",
            youtube_url="https://www.youtube.com/watch?v=ygS_Cwng7IU&index=225&list=LLTMldtPNnazX0I1Y1Mctdfg"),
    song.Song(title="Pray For Me",
            artist_name="The Weeknd, Kendrick Lamar",
            youtube_url="https://www.youtube.com/watch?v=K5xERXE7pxI&list=LLTMldtPNnazX0I1Y1Mctdfg&index=190"),
    song.Song(title="Fake Love",
            artist_name="Drake",
            youtube_url="https://www.youtube.com/watch?v=7ZX3eAgXAmg&index=289&list=LLTMldtPNnazX0I1Y1Mctdfg"),
    song.Song(title="Every Day",
            artist_name="Jeremy Zucker",
            youtube_url="https://www.youtube.com/watch?v=t35xCbH0yio&list=LLTMldtPNnazX0I1Y1Mctdfg&index=256"),
    song.Song(title="Numbers",
            artist_name="Logic",
            youtube_url="https://www.youtube.com/watch?v=UTUMgGBNpOs&index=609&list=LLTMldtPNnazX0I1Y1Mctdfg"),
    song.Song(title="On and On",
            artist_name="Cartoon (feat. Daniel Levi)",
            youtube_url="https://www.youtube.com/watch?v=K4DyBUG242c")
]